version: "3"
volumes: 
  mysql-data:
  gem_home:

services:
  mysql:
    image: mysql:5.7.25
    ports: 
      - 23306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  rails:
    build: .
    image: rails-mysql
    ports: 
      - 23000:3000
    volumes:
      - .:/rails-mysql
      - gem_home:/usr/local/bundle
      - /app/.git
    depends_on:
      - mysql
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
